/**
 * Representative Foundation Lab suite.
 * Behavioral diversity, not quantity. Used to write fixtures/foundation/*.json.
 */
(function (root, factory) {
  const api = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  if (root) root.FOUNDATION_LAB_SUITE_DEFS = api.FOUNDATION_LAB_SUITE_DEFS;
})(typeof globalThis !== 'undefined' ? globalThis : (typeof window !== 'undefined' ? window : null), function () {
  'use strict';

  function land(qty, name, type, colors) {
    return { name, qty, cmc: 0, type, roleTags: ['Land'], oracleText: '', colors };
  }

  function card(name, opts) {
    const o = opts || {};
    return {
      name,
      qty: o.qty || 1,
      cmc: o.cmc == null ? 2 : o.cmc,
      type: o.type || 'Instant',
      roleTags: o.roleTags || [],
      oracleText: o.oracle || o.oracleText || '',
      colors: o.colors || [],
      ir: o.ir || null,
    };
  }

  function cmd(name, opts) {
    const o = opts || {};
    return {
      name,
      qty: 1,
      cmc: o.cmc == null ? 4 : o.cmc,
      type: o.type || 'Legendary Creature',
      roleTags: o.roleTags || [],
      oracleText: o.oracle || '',
      colors: o.colors || [],
      isCommander: true,
    };
  }

  const FOUNDATION_LAB_SUITE_DEFS = [
    {
      id: 'krenko-aggro',
      name: 'Krenko Aggro',
      archetype: 'aggro',
      commander: 'Krenko, Mob Boss',
      colorIdentity: ['R'],
      golden: ['color_identity_stack_vulnerability'],
      plan: {
        winConditionId: 'wincon.combat',
        primaryStrategyId: 'strategy.tokens',
        competition: 'Focused',
        playstyleS: -5,
        targetCastTurn: 3,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'low',
        keyCards: [{ name: 'Krenko, Mob Boss' }],
      },
      notes: 'Mono-red aggro. Stack/graveyard gaps should be color-identity vulnerabilities, not blanket deficiencies.',
      expected: { closeGameMode: 'combat', stackKind: 'color_identity_vulnerability' },
      cards: [
        cmd('Krenko, Mob Boss', { cmc: 3, colors: ['R'], oracle: 'Goblin tokens.' }),
        card('Lightning Bolt', { cmc: 1, roleTags: ['Burn', 'Removal'], oracle: 'Lightning Bolt deals 3 damage to any target.', colors: ['R'] }),
        card('Impact Tremors', { cmc: 2, type: 'Enchantment', roleTags: ['Ping'], oracle: 'Whenever a creature enters the battlefield under your control, it deals 1 damage to each opponent.', colors: ['R'] }),
        card('Sol Ring', { cmc: 1, type: 'Artifact', roleTags: ['Ramp', 'Mana Rock'], oracle: '{T}: Add {C}{C}.' }),
        card('Hoarding Dragon', { cmc: 5, type: 'Creature', roleTags: [], oracle: 'Flying. A slow beater off-plan for goblin aggro.', colors: ['R'] }),
        land(36, 'Mountain', 'Basic Land — Mountain', ['R']),
      ],
    },
    {
      id: 'talrand-control',
      name: 'Talrand Control',
      archetype: 'control',
      commander: 'Talrand, Sky Summoner',
      colorIdentity: ['U'],
      plan: {
        winConditionId: 'wincon.value',
        primaryStrategyId: 'strategy.control',
        competition: 'High',
        playstyleS: 5,
        targetCastTurn: 4,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'med',
        keyCards: [{ name: 'Rhystic Study' }],
      },
      notes: 'Mono-blue control. Creature answers may be a color-identity vulnerability; stack should be a strength.',
      expected: { closeGameMode: 'value' },
      cards: [
        cmd('Talrand, Sky Summoner', { cmc: 4, colors: ['U'] }),
        card('Counterspell', { roleTags: ['Counterspell'], oracle: 'Counter target spell.', colors: ['U'] }),
        card('Force of Will', { cmc: 5, roleTags: ['Counterspell'], oracle: 'You may pay 1 life and exile a blue card from your hand rather than pay this spell\'s mana cost. Counter target spell.', colors: ['U'] }),
        card('Rhystic Study', { cmc: 3, type: 'Enchantment', roleTags: ['Card Draw'], oracle: 'Whenever an opponent casts a spell, you may draw a card unless that player pays {1}.', colors: ['U'] }),
        card('Cyclonic Rift', { roleTags: ['Board Wipe', 'Bounce'], oracle: 'Return target nonland permanent you don\'t control to its owner\'s hand. Overload {6}{U}', colors: ['U'] }),
        card('Sol Ring', { cmc: 1, type: 'Artifact', roleTags: ['Ramp', 'Mana Rock'], oracle: '{T}: Add {C}{C}.' }),
        land(36, 'Island', 'Basic Land — Island', ['U']),
      ],
    },
    {
      id: 'korvold-midrange',
      name: 'Korvold Midrange',
      archetype: 'midrange',
      commander: 'Korvold, Fae-Cursed King',
      colorIdentity: ['B', 'R', 'G'],
      plan: {
        winConditionId: 'wincon.value',
        primaryStrategyId: 'strategy.sacrifice',
        competition: 'Focused',
        playstyleS: 1,
        targetCastTurn: 4,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'med',
        keyCards: [{ name: 'Mayhem Devil' }],
      },
      notes: 'Jund midrange / food-chain adjacent.',
      expected: { closeGameMode: 'value' },
      cards: [
        cmd('Korvold, Fae-Cursed King', { cmc: 5, colors: ['B', 'R', 'G'] }),
        card('Mayhem Devil', { cmc: 3, type: 'Creature', roleTags: ['Ping'], oracle: 'Whenever a player sacrifices a permanent, Mayhem Devil deals 1 damage to any target.', colors: ['B', 'R'] }),
        card('Cultivate', { cmc: 3, type: 'Sorcery', roleTags: ['Ramp'], oracle: 'Search your library for up to two basic land cards.', colors: ['G'] }),
        card('Eternal Witness', { cmc: 3, type: 'Creature', roleTags: ['Recursion'], oracle: 'When this creature enters, return target card from your graveyard to your hand.', colors: ['G'] }),
        card('Beast Within', { cmc: 3, type: 'Instant', roleTags: ['Removal'], oracle: 'Destroy target permanent.', colors: ['G'] }),
        land(12, 'Forest', 'Basic Land — Forest', ['G']),
        land(12, 'Swamp', 'Basic Land — Swamp', ['B']),
        land(12, 'Mountain', 'Basic Land — Mountain', ['R']),
      ],
    },
    {
      id: 'rhys-tokens',
      name: 'Rhys Tokens',
      archetype: 'tokens',
      commander: 'Rhys the Redeemed',
      colorIdentity: ['W', 'G'],
      plan: {
        winConditionId: 'wincon.combat',
        primaryStrategyId: 'strategy.tokens',
        competition: 'Casual',
        playstyleS: -2,
        targetCastTurn: 2,
        castingPattern: 'one_per_turn',
        tutorPreference: 'rather_not',
        protectionImportance: 'med',
        keyCards: [{ name: 'Secure the Wastes' }],
      },
      notes: 'Casual tokens. Keep Going need should be lower than fast combo.',
      expected: { closeGameMode: 'combat' },
      cards: [
        cmd('Rhys the Redeemed', { cmc: 2, colors: ['W', 'G'], roleTags: ['Token Maker'] }),
        card('Secure the Wastes', { cmc: 1, type: 'Instant', roleTags: ['Token Maker'], oracle: 'Create X 1/1 white Warrior creature tokens.', colors: ['W'] }),
        card('Wrath of God', { cmc: 4, type: 'Sorcery', roleTags: ['Board Wipe'], oracle: 'Destroy all creatures.', colors: ['W'] }),
        card('Swords to Plowshares', { cmc: 1, roleTags: ['Removal'], oracle: 'Exile target creature.', colors: ['W'] }),
        card('Skullclamp', { cmc: 1, type: 'Artifact', roleTags: ['Card Draw'], oracle: 'Whenever equipped creature dies, draw two cards.' }),
        land(18, 'Plains', 'Basic Land — Plains', ['W']),
        land(18, 'Forest', 'Basic Land — Forest', ['G']),
      ],
    },
    {
      id: 'rafiq-voltron',
      name: 'Rafiq Voltron',
      archetype: 'voltron',
      commander: 'Rafiq of the Many',
      colorIdentity: ['W', 'U', 'G'],
      golden: ['shared_capacity', 'user_target_override'],
      plan: {
        winConditionId: 'wincon.commander_damage',
        primaryStrategyId: 'strategy.voltron',
        competition: 'Focused',
        playstyleS: -2,
        targetCastTurn: 3,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'high',
        keyCards: [{ name: 'Rafiq of the Many' }],
        confirmedRoles: [{ label: 'Card Draw', target: 6, checked: true }],
      },
      notes: 'Voltron: protection vs interaction share capacity. User Card Draw target 6 overrides the proposal.',
      expected: { closeGameMode: 'commander_damage', userTarget: 6 },
      cards: [
        cmd('Rafiq of the Many', { cmc: 3, colors: ['W', 'U', 'G'] }),
        card('Swiftfoot Boots', { type: 'Artifact', roleTags: ['Protection'], oracle: 'Equipped creature has hexproof and haste.' }),
        card('Swords to Plowshares', { cmc: 1, roleTags: ['Removal'], oracle: 'Exile target creature.', colors: ['W'] }),
        card('Rhystic Study', { cmc: 3, type: 'Enchantment', roleTags: ['Card Draw'], oracle: 'Whenever an opponent casts a spell, you may draw a card.', colors: ['U'] }),
        card('Cultivate', { cmc: 3, type: 'Sorcery', roleTags: ['Ramp'], oracle: 'Search your library for up to two basic land cards.', colors: ['G'] }),
        land(12, 'Forest', 'Basic Land — Forest', ['G']),
        land(12, 'Plains', 'Basic Land — Plains', ['W']),
        land(12, 'Island', 'Basic Land — Island', ['U']),
      ],
    },
    {
      id: 'teysa-aristocrats',
      name: 'Teysa Aristocrats',
      archetype: 'aristocrats',
      commander: 'Teysa Karlov',
      colorIdentity: ['W', 'B'],
      golden: ['synergy_measurable'],
      plan: {
        winConditionId: 'wincon.life_drain',
        primaryStrategyId: 'strategy.sacrifice',
        competition: 'Focused',
        playstyleS: 0,
        targetCastTurn: 4,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'med',
        keyCards: [{ name: 'Blood Artist' }],
      },
      notes: 'Synergistic but independently modest drain pieces should show plan overlap.',
      expected: { closeGameMode: 'life_drain' },
      cards: [
        cmd('Teysa Karlov', { cmc: 4, colors: ['W', 'B'] }),
        card('Viscera Seer', { cmc: 1, type: 'Creature', roleTags: ['Sac Outlet'], oracle: 'Sacrifice a creature: Scry 1.', colors: ['B'] }),
        card('Blood Artist', { cmc: 2, type: 'Creature', roleTags: ['Drain'], oracle: 'Whenever Blood Artist or another creature dies, target player loses 1 life and you gain 1 life.', colors: ['B'] }),
        card('Zulaport Cutthroat', { cmc: 2, type: 'Creature', roleTags: ['Drain'], oracle: 'Whenever Zulaport Cutthroat or another creature you control dies, each opponent loses 1 life and you gain 1 life.', colors: ['B'] }),
        card('Swords to Plowshares', { cmc: 1, roleTags: ['Removal'], oracle: 'Exile target creature.', colors: ['W'] }),
        land(18, 'Plains', 'Basic Land — Plains', ['W']),
        land(18, 'Swamp', 'Basic Land — Swamp', ['B']),
      ],
    },
    {
      id: 'meren-reanimator',
      name: 'Meren Reanimator',
      archetype: 'reanimator',
      commander: 'Meren of Clan Nel Toth',
      colorIdentity: ['B', 'G'],
      golden: ['reanimator_keep_going', 'no_full_multirole'],
      plan: {
        winConditionId: 'wincon.combat',
        primaryStrategyId: 'strategy.reanimator',
        competition: 'Focused',
        playstyleS: 1,
        targetCastTurn: 5,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'med',
        keyCards: [{ name: 'Animate Dead' }],
      },
      notes: 'Recursion should credit Keep Going and Resources, not full credit on every theoretical role.',
      expected: { closeGameMode: 'combat', recursionKeepGoing: true },
      cards: [
        cmd('Meren of Clan Nel Toth', { cmc: 5, colors: ['B', 'G'], roleTags: ['Recursion'] }),
        card('Animate Dead', { type: 'Enchantment', roleTags: ['Reanimate', 'Recursion'], oracle: 'Return target creature card from a graveyard to the battlefield.', colors: ['B'] }),
        card('Victimize', { cmc: 3, type: 'Sorcery', roleTags: ['Reanimate', 'Recursion'], oracle: 'Sacrifice a creature. Return two creature cards from your graveyard to the battlefield.', colors: ['B'] }),
        card('Eternal Witness', { cmc: 3, type: 'Creature', roleTags: ['Recursion'], oracle: 'When this creature enters, return target card from your graveyard to your hand.', colors: ['G'] }),
        card('Entomb', { cmc: 1, type: 'Instant', roleTags: ['Tutor'], oracle: 'Search your library for a card, put that card into your graveyard.', colors: ['B'] }),
        card('Phyrexian Reclamation', { cmc: 1, type: 'Enchantment', roleTags: ['Recursion', 'Card Draw'], oracle: 'Pay life, return target creature card from your graveyard to your hand. Recurring value engine.', colors: ['B'] }),
        card('Cultivate', { cmc: 3, type: 'Sorcery', roleTags: ['Ramp'], oracle: 'Search your library for up to two basic land cards.', colors: ['G'] }),
        land(18, 'Swamp', 'Basic Land — Swamp', ['B']),
        land(18, 'Forest', 'Basic Land — Forest', ['G']),
      ],
    },
    {
      id: 'sidisi-graveyard',
      name: 'Sidisi Graveyard',
      archetype: 'graveyard',
      commander: 'Sidisi, Brood Tyrant',
      colorIdentity: ['B', 'G', 'U'],
      plan: {
        winConditionId: 'wincon.combat',
        primaryStrategyId: 'strategy.reanimator',
        competition: 'Focused',
        playstyleS: 2,
        targetCastTurn: 4,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'med',
        keyCards: [{ name: 'Life from the Loam' }],
      },
      notes: 'Self-mill graveyard value, distinct from pure reanimator.',
      expected: { closeGameMode: 'combat' },
      cards: [
        cmd('Sidisi, Brood Tyrant', { cmc: 4, colors: ['B', 'G', 'U'] }),
        card('Life from the Loam', { type: 'Sorcery', roleTags: ['Recursion'], oracle: 'Return up to three land cards from your graveyard to your hand. Dredge 3.', colors: ['G'] }),
        card('Eternal Witness', { cmc: 3, type: 'Creature', roleTags: ['Recursion'], oracle: 'When this creature enters, return target card from your graveyard to your hand.', colors: ['G'] }),
        card('Counterspell', { roleTags: ['Counterspell'], oracle: 'Counter target spell.', colors: ['U'] }),
        land(12, 'Island', 'Basic Land — Island', ['U']),
        land(12, 'Swamp', 'Basic Land — Swamp', ['B']),
        land(12, 'Forest', 'Basic Land — Forest', ['G']),
      ],
    },
    {
      id: 'kykar-spellslinger',
      name: 'Kykar Spellslinger',
      archetype: 'spellslinger',
      commander: 'Kykar, Wind\'s Fury',
      colorIdentity: ['W', 'U', 'R'],
      plan: {
        winConditionId: 'wincon.combat',
        primaryStrategyId: 'strategy.spellslinger',
        competition: 'Focused',
        playstyleS: 2,
        targetCastTurn: 4,
        castingPattern: 'several_in_one_turn',
        tutorPreference: 'fine',
        protectionImportance: 'med',
        keyCards: [{ name: 'Guttersnipe' }],
      },
      notes: 'Several spells in one turn — mana access uses sum CMC for key cards.',
      expected: { closeGameMode: 'combat', castingPattern: 'several_in_one_turn' },
      cards: [
        cmd('Kykar, Wind\'s Fury', { cmc: 4, colors: ['W', 'U', 'R'] }),
        card('Brainstorm', { cmc: 1, roleTags: ['Card Draw'], oracle: 'Draw three cards, then put two cards from your hand on top of your library.', colors: ['U'] }),
        card('Guttersnipe', { cmc: 3, type: 'Creature', roleTags: ['Ping'], oracle: 'Whenever you cast an instant or sorcery spell, Guttersnipe deals 2 damage to each opponent.', colors: ['R'] }),
        card('Counterspell', { roleTags: ['Counterspell'], oracle: 'Counter target spell.', colors: ['U'] }),
        card('Swords to Plowshares', { cmc: 1, roleTags: ['Removal'], oracle: 'Exile target creature.', colors: ['W'] }),
        land(12, 'Island', 'Basic Land — Island', ['U']),
        land(12, 'Mountain', 'Basic Land — Mountain', ['R']),
        land(12, 'Plains', 'Basic Land — Plains', ['W']),
      ],
    },
    {
      id: 'gitrog-combo',
      name: 'Gitrog Lands Combo',
      archetype: 'combo',
      commander: 'The Gitrog Monster',
      colorIdentity: ['B', 'G'],
      golden: ['declared_wincon_not_edhrec'],
      plan: {
        winConditionId: 'wincon.combo',
        primaryStrategyId: 'strategy.landfall',
        competition: 'High',
        playstyleS: 3,
        targetCastTurn: 4,
        castingPattern: 'several_in_one_turn',
        tutorPreference: 'fine',
        protectionImportance: 'high',
        keyCards: [{ name: 'Dakmor Salvage' }, { name: 'Life from the Loam' }],
      },
      notes: 'Declared combo wincon must not be replaced by EDHREC preferences.',
      expected: { closeGameMode: 'combo', winConditionId: 'wincon.combo' },
      cards: [
        cmd('The Gitrog Monster', { cmc: 5, colors: ['B', 'G'] }),
        card('Dakmor Salvage', { cmc: 0, type: 'Land', roleTags: ['Land'], oracle: 'Dredge 2', colors: ['B'] }),
        card('Life from the Loam', { type: 'Sorcery', roleTags: ['Recursion'], oracle: 'Return three land cards from your graveyard to your hand. Dredge 3.', colors: ['G'] }),
        card('Dark Ritual', { cmc: 1, type: 'Instant', roleTags: ['Ramp'], oracle: 'Add {B}{B}{B}.', colors: ['B'] }),
        card('Eternal Witness', { cmc: 3, type: 'Creature', roleTags: ['Recursion'], oracle: 'When this creature enters, return target card from your graveyard to your hand.', colors: ['G'] }),
        land(18, 'Forest', 'Basic Land — Forest', ['G']),
        land(16, 'Swamp', 'Basic Land — Swamp', ['B']),
      ],
    },
    {
      id: 'kinnan-cedh',
      name: 'Kinnan Fast Combo cEDH',
      archetype: 'fast-combo',
      commander: 'Kinnan, Bonder Prodigy',
      colorIdentity: ['G', 'U'],
      golden: ['combo_keep_going_bump'],
      plan: {
        winConditionId: 'wincon.combo',
        primaryStrategyId: 'strategy.spellslinger',
        competition: 'cEDH',
        playstyleS: 4,
        targetCastTurn: 2,
        castingPattern: 'several_in_one_turn',
        tutorPreference: 'fine',
        protectionImportance: 'high',
        keyCards: [{ name: 'Basalt Monolith' }, { name: 'Dramatic Reversal' }],
      },
      notes: 'cEDH fast combo — Keep Going expectations should rise vs casual tokens.',
      expected: { closeGameMode: 'combo', keepGoingExpectationBump: true },
      cards: [
        cmd('Kinnan, Bonder Prodigy', { cmc: 2, colors: ['G', 'U'] }),
        card('Basalt Monolith', { cmc: 3, type: 'Artifact', roleTags: ['Ramp', 'Mana Rock'], oracle: '{T}: Add {C}{C}{C}.' }),
        card('Dramatic Reversal', { type: 'Instant', roleTags: ['Combo'], oracle: 'Untap all nonland permanents you control. you win the game.', colors: ['U'] }),
        card('Rhystic Study', { cmc: 3, type: 'Enchantment', roleTags: ['Card Draw'], oracle: 'Whenever an opponent casts a spell, you may draw a card unless that player pays {1}.', colors: ['U'] }),
        card('Swan Song', { cmc: 1, roleTags: ['Counterspell'], oracle: 'Counter target enchantment, instant, or sorcery spell.', colors: ['U'] }),
        card('Force of Will', { cmc: 5, roleTags: ['Counterspell'], oracle: 'You may pay 1 life and exile a blue card from your hand rather than pay this spell\'s mana cost. Counter target spell.', colors: ['U'] }),
        land(16, 'Island', 'Basic Land — Island', ['U']),
        land(14, 'Forest', 'Basic Land — Forest', ['G']),
      ],
    },
    {
      id: 'omnath-ramp',
      name: 'Omnath Ramp-Heavy',
      archetype: 'ramp-heavy',
      commander: 'Omnath, Locus of Mana',
      colorIdentity: ['G'],
      plan: {
        winConditionId: 'wincon.combat',
        primaryStrategyId: 'strategy.landfall',
        competition: 'Casual',
        playstyleS: -1,
        targetCastTurn: 3,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'low',
        keyCards: [{ name: 'Omnath, Locus of Mana' }],
      },
      notes: 'Ramp-heavy mono-green. Mana access should not be scored as a land quota.',
      expected: { closeGameMode: 'combat' },
      cards: [
        cmd('Omnath, Locus of Mana', { cmc: 3, colors: ['G'] }),
        card('Cultivate', { cmc: 3, type: 'Sorcery', roleTags: ['Ramp'], oracle: 'Search your library for up to two basic land cards.', colors: ['G'] }),
        card('Rampant Growth', { type: 'Sorcery', roleTags: ['Ramp'], oracle: 'Search your library for a basic land card.', colors: ['G'] }),
        card('Nature\'s Lore', { type: 'Sorcery', roleTags: ['Ramp'], oracle: 'Search your library for a Forest card.', colors: ['G'] }),
        card('Harmonize', { cmc: 4, type: 'Sorcery', roleTags: ['Card Draw'], oracle: 'Draw three cards.', colors: ['G'] }),
        card('Beast Within', { cmc: 3, type: 'Instant', roleTags: ['Removal'], oracle: 'Destroy target permanent.', colors: ['G'] }),
        land(38, 'Forest', 'Basic Land — Forest', ['G']),
      ],
    },
    {
      id: 'grand-arbiter-stax',
      name: 'Grand Arbiter Stax',
      archetype: 'stax',
      commander: 'Grand Arbiter Augustin IV',
      colorIdentity: ['W', 'U'],
      plan: {
        winConditionId: 'wincon.value',
        primaryStrategyId: 'strategy.stax',
        competition: 'High',
        playstyleS: 4,
        targetCastTurn: 3,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'high',
        keyCards: [{ name: 'Grand Arbiter Augustin IV' }],
      },
      notes: 'Stax — interaction/keep-going needs should sit above casual tokens.',
      expected: { closeGameMode: 'value' },
      cards: [
        cmd('Grand Arbiter Augustin IV', { cmc: 4, colors: ['W', 'U'] }),
        card('Counterspell', { roleTags: ['Counterspell'], oracle: 'Counter target spell.', colors: ['U'] }),
        card('Swords to Plowshares', { cmc: 1, roleTags: ['Removal'], oracle: 'Exile target creature.', colors: ['W'] }),
        card('Smothering Tithe', { cmc: 4, type: 'Enchantment', roleTags: ['Ramp', 'Card Draw'], oracle: 'Whenever an opponent draws a card, that player may pay {2}. If they don\'t, you create a Treasure token.', colors: ['W'] }),
        card('Wrath of God', { cmc: 4, type: 'Sorcery', roleTags: ['Board Wipe'], oracle: 'Destroy all creatures.', colors: ['W'] }),
        land(18, 'Plains', 'Basic Land — Plains', ['W']),
        land(18, 'Island', 'Basic Land — Island', ['U']),
      ],
    },
    {
      id: 'urza-artifacts',
      name: 'Urza Artifacts',
      archetype: 'artifact-focused',
      commander: 'Urza, Lord High Artificer',
      colorIdentity: ['U'],
      plan: {
        winConditionId: 'wincon.combo',
        primaryStrategyId: 'strategy.goodstuff',
        competition: 'High',
        playstyleS: 3,
        targetCastTurn: 4,
        castingPattern: 'several_in_one_turn',
        tutorPreference: 'fine',
        protectionImportance: 'high',
        keyCards: [{ name: 'Basalt Monolith' }],
      },
      notes: 'Artifact-focused combo-control.',
      expected: { closeGameMode: 'combo' },
      cards: [
        cmd('Urza, Lord High Artificer', { cmc: 4, colors: ['U'] }),
        card('Sol Ring', { cmc: 1, type: 'Artifact', roleTags: ['Ramp', 'Mana Rock'], oracle: '{T}: Add {C}{C}.' }),
        card('Basalt Monolith', { cmc: 3, type: 'Artifact', roleTags: ['Ramp', 'Mana Rock'], oracle: '{T}: Add {C}{C}{C}.' }),
        card('Rhystic Study', { cmc: 3, type: 'Enchantment', roleTags: ['Card Draw'], oracle: 'Whenever an opponent casts a spell, you may draw a card unless that player pays {1}.', colors: ['U'] }),
        card('Counterspell', { roleTags: ['Counterspell'], oracle: 'Counter target spell.', colors: ['U'] }),
        land(26, 'Island', 'Basic Land — Island', ['U']),
      ],
    },
    {
      id: 'sythis-enchantments',
      name: 'Sythis Enchantress',
      archetype: 'enchantment-focused',
      commander: 'Sythis, Harvest\'s Hand',
      colorIdentity: ['G', 'W'],
      plan: {
        winConditionId: 'wincon.combat',
        primaryStrategyId: 'strategy.enchantress',
        competition: 'Focused',
        playstyleS: 0,
        targetCastTurn: 2,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'med',
        keyCards: [{ name: 'Enchantress\'s Presence' }],
      },
      notes: 'Enchantment-focused value.',
      expected: { closeGameMode: 'combat' },
      cards: [
        cmd('Sythis, Harvest\'s Hand', { cmc: 2, colors: ['G', 'W'], type: 'Legendary Enchantment Creature' }),
        card('Enchantress\'s Presence', { cmc: 3, type: 'Enchantment', roleTags: ['Card Draw'], oracle: 'Whenever you cast an enchantment spell, draw a card.', colors: ['G'] }),
        card('Sterling Grove', { type: 'Enchantment', roleTags: ['Protection', 'Tutor'], oracle: 'Other enchantments you control have hexproof.', colors: ['G', 'W'] }),
        card('Swords to Plowshares', { cmc: 1, roleTags: ['Removal'], oracle: 'Exile target creature.', colors: ['W'] }),
        card('Sol Ring', { cmc: 1, type: 'Artifact', roleTags: ['Ramp', 'Mana Rock'], oracle: '{T}: Add {C}{C}.' }),
        land(16, 'Forest', 'Basic Land — Forest', ['G']),
        land(12, 'Plains', 'Basic Land — Plains', ['W']),
      ],
    },
    {
      id: 'edgar-tribal',
      name: 'Edgar Vampire Tribal',
      archetype: 'tribal',
      commander: 'Edgar Markov',
      colorIdentity: ['W', 'B', 'R'],
      plan: {
        winConditionId: 'wincon.combat',
        primaryStrategyId: 'strategy.tribal',
        competition: 'Casual',
        playstyleS: -3,
        targetCastTurn: 6,
        castingPattern: 'one_per_turn',
        tutorPreference: 'rather_not',
        protectionImportance: 'med',
        keyCards: [{ name: 'Captivating Vampire' }],
        planTypePicks: { 'strategy.tribal': ['vampire'] },
      },
      notes: 'Tribal combat.',
      expected: { closeGameMode: 'combat' },
      cards: [
        cmd('Edgar Markov', { cmc: 6, colors: ['W', 'B', 'R'] }),
        card('Captivating Vampire', { cmc: 3, type: 'Creature — Vampire', roleTags: ['Anthem'], oracle: 'Other Vampire creatures you control get +1/+1.', colors: ['B'] }),
        card('Swords to Plowshares', { cmc: 1, roleTags: ['Removal'], oracle: 'Exile target creature.', colors: ['W'] }),
        card('Faithless Looting', { cmc: 1, type: 'Sorcery', roleTags: ['Card Draw'], oracle: 'Draw two cards, then discard two cards.', colors: ['R'] }),
        land(12, 'Plains', 'Basic Land — Plains', ['W']),
        land(12, 'Swamp', 'Basic Land — Swamp', ['B']),
        land(12, 'Mountain', 'Basic Land — Mountain', ['R']),
      ],
    },
    {
      id: 'azusa-lands',
      name: 'Azusa Lands',
      archetype: 'lands',
      commander: 'Azusa, Lost but Seeking',
      colorIdentity: ['G'],
      plan: {
        winConditionId: 'wincon.combat',
        primaryStrategyId: 'strategy.landfall',
        competition: 'Focused',
        playstyleS: 0,
        targetCastTurn: 2,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'med',
        keyCards: [{ name: 'Azusa, Lost but Seeking' }],
      },
      notes: 'Lands-matter. Mana access is execute-the-plan, not land count.',
      expected: { closeGameMode: 'combat' },
      cards: [
        cmd('Azusa, Lost but Seeking', { cmc: 3, colors: ['G'] }),
        card('Exploration', { cmc: 1, type: 'Enchantment', roleTags: ['Ramp'], oracle: 'You may play an additional land on each of your turns.', colors: ['G'] }),
        card('Oracle of Mul Daya', { cmc: 4, type: 'Creature', roleTags: ['Ramp', 'Card Draw'], oracle: 'You may play an additional land on each of your turns.', colors: ['G'] }),
        card('Cultivate', { cmc: 3, type: 'Sorcery', roleTags: ['Ramp'], oracle: 'Search your library for up to two basic land cards.', colors: ['G'] }),
        land(28, 'Forest', 'Basic Land — Forest', ['G']),
      ],
    },
    {
      id: 'omnath-budget',
      name: 'Omnath Low-Budget',
      archetype: 'low-budget',
      commander: 'Omnath, Locus of Mana',
      colorIdentity: ['G'],
      golden: ['budget_constraint'],
      plan: {
        winConditionId: 'wincon.combat',
        primaryStrategyId: 'strategy.landfall',
        competition: 'Casual',
        playstyleS: 0,
        targetCastTurn: 3,
        castingPattern: 'one_per_turn',
        tutorPreference: 'rather_not',
        protectionImportance: 'low',
        roughMaxPerCardBudgetUsd: 3,
        keyCards: [{ name: 'Rampant Growth' }],
      },
      notes: 'Low-budget mono-green. Interaction gaps may be budget constraints when in-color answers exist above the cap.',
      expected: { closeGameMode: 'combat' },
      cards: [
        cmd('Omnath, Locus of Mana', { cmc: 3, colors: ['G'] }),
        card('Rampant Growth', { type: 'Sorcery', roleTags: ['Ramp'], oracle: 'Search your library for a basic land card.', colors: ['G'] }),
        card('Giant Growth', { cmc: 1, type: 'Instant', roleTags: [], oracle: 'Target creature gets +3/+3 until end of turn.', colors: ['G'] }),
        land(38, 'Forest', 'Basic Land — Forest', ['G']),
      ],
    },
    {
      id: 'norin-mono-red',
      name: 'Norin Mono-Red',
      archetype: 'mono-color',
      commander: 'Norin the Wary',
      colorIdentity: ['R'],
      golden: ['color_identity_stack_vulnerability'],
      plan: {
        winConditionId: 'wincon.combat',
        primaryStrategyId: 'strategy.goodstuff',
        competition: 'Focused',
        playstyleS: -4,
        targetCastTurn: 1,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'low',
        keyCards: [{ name: 'Norin the Wary' }],
      },
      notes: 'Mono-red: stack and graveyard interaction are color-identity vulnerabilities.',
      expected: { stackKind: 'color_identity_vulnerability' },
      cards: [
        cmd('Norin the Wary', { cmc: 1, colors: ['R'] }),
        card('Chaos Warp', { cmc: 3, type: 'Instant', roleTags: ['Removal'], oracle: 'Exile target permanent, then its owner reveals the top card of their library.', colors: ['R'] }),
        card('Blasphemous Act', { cmc: 9, type: 'Sorcery', roleTags: ['Board Wipe'], oracle: 'Blasphemous Act deals 13 damage to each creature.', colors: ['R'] }),
        card('Faithless Looting', { cmc: 1, type: 'Sorcery', roleTags: ['Card Draw'], oracle: 'Draw two cards, then discard two cards.', colors: ['R'] }),
        land(38, 'Mountain', 'Basic Land — Mountain', ['R']),
      ],
    },
    {
      id: 'kinnan-two-color',
      name: 'Kinnan Two-Color Value',
      archetype: 'two-color',
      commander: 'Kinnan, Bonder Prodigy',
      colorIdentity: ['G', 'U'],
      plan: {
        winConditionId: 'wincon.value',
        primaryStrategyId: 'strategy.goodstuff',
        competition: 'Focused',
        playstyleS: 1,
        targetCastTurn: 2,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'med',
        keyCards: [{ name: 'Kinnan, Bonder Prodigy' }],
      },
      notes: 'Simic two-color, distinct from the cEDH combo list.',
      expected: { closeGameMode: 'value' },
      cards: [
        cmd('Kinnan, Bonder Prodigy', { cmc: 2, colors: ['G', 'U'] }),
        card('Cultivate', { cmc: 3, type: 'Sorcery', roleTags: ['Ramp'], oracle: 'Search your library for up to two basic land cards.', colors: ['G'] }),
        card('Rhystic Study', { cmc: 3, type: 'Enchantment', roleTags: ['Card Draw'], oracle: 'Whenever an opponent casts a spell, you may draw a card unless that player pays {1}.', colors: ['U'] }),
        card('Counterspell', { roleTags: ['Counterspell'], oracle: 'Counter target spell.', colors: ['U'] }),
        card('Beast Within', { cmc: 3, type: 'Instant', roleTags: ['Removal'], oracle: 'Destroy target permanent.', colors: ['G'] }),
        land(18, 'Forest', 'Basic Land — Forest', ['G']),
        land(18, 'Island', 'Basic Land — Island', ['U']),
      ],
    },
    {
      id: 'sisay-fivecolor',
      name: 'Sisay Five-Color Legends',
      archetype: 'five-color',
      commander: 'Sisay, Weatherlight Captain',
      colorIdentity: ['W', 'U', 'B', 'R', 'G'],
      plan: {
        winConditionId: 'wincon.combat',
        primaryStrategyId: 'strategy.goodstuff',
        competition: 'High',
        playstyleS: 2,
        targetCastTurn: 3,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'high',
        keyCards: [{ name: 'Sisay, Weatherlight Captain' }],
      },
      notes: 'Five-color identity should not invent color-identity stack vulnerabilities.',
      expected: { closeGameMode: 'combat' },
      cards: [
        cmd('Sisay, Weatherlight Captain', { cmc: 3, colors: ['W', 'U', 'B', 'R', 'G'] }),
        card('Sol Ring', { cmc: 1, type: 'Artifact', roleTags: ['Ramp', 'Mana Rock'], oracle: '{T}: Add {C}{C}.' }),
        card('Rhystic Study', { cmc: 3, type: 'Enchantment', roleTags: ['Card Draw'], oracle: 'Whenever an opponent casts a spell, you may draw a card unless that player pays {1}.', colors: ['U'] }),
        card('Swords to Plowshares', { cmc: 1, roleTags: ['Removal'], oracle: 'Exile target creature.', colors: ['W'] }),
        card('Counterspell', { roleTags: ['Counterspell'], oracle: 'Counter target spell.', colors: ['U'] }),
        card('Demonic Tutor', { type: 'Sorcery', roleTags: ['Tutor'], oracle: 'Search your library for a card, put that card into your hand.', colors: ['B'] }),
        land(6, 'Plains', 'Basic Land — Plains', ['W']),
        land(6, 'Island', 'Basic Land — Island', ['U']),
        land(6, 'Swamp', 'Basic Land — Swamp', ['B']),
        land(6, 'Mountain', 'Basic Land — Mountain', ['R']),
        land(6, 'Forest', 'Basic Land — Forest', ['G']),
      ],
    },
    {
      id: 'kenrith-cedh-high',
      name: 'Kenrith High-Power',
      archetype: 'cedh',
      commander: 'Kenrith, the Returned King',
      colorIdentity: ['W', 'U', 'B', 'R', 'G'],
      plan: {
        winConditionId: 'wincon.combo',
        primaryStrategyId: 'strategy.goodstuff',
        competition: 'cEDH',
        playstyleS: 3,
        targetCastTurn: 5,
        castingPattern: 'several_in_one_turn',
        tutorPreference: 'fine',
        protectionImportance: 'high',
        keyCards: [{ name: 'Kenrith, the Returned King' }],
      },
      notes: 'Five-color high-power / cEDH-adjacent. Interaction need should sit at the top of the suite.',
      expected: { closeGameMode: 'combo' },
      cards: [
        cmd('Kenrith, the Returned King', { cmc: 5, colors: ['W', 'U', 'B', 'R', 'G'] }),
        card('Demonic Tutor', { type: 'Sorcery', roleTags: ['Tutor'], oracle: 'Search your library for a card, put that card into your hand.', colors: ['B'] }),
        card('Force of Will', { cmc: 5, roleTags: ['Counterspell'], oracle: 'You may pay 1 life and exile a blue card from your hand rather than pay this spell\'s mana cost. Counter target spell.', colors: ['U'] }),
        card('Swords to Plowshares', { cmc: 1, roleTags: ['Removal'], oracle: 'Exile target creature.', colors: ['W'] }),
        card('Rhystic Study', { cmc: 3, type: 'Enchantment', roleTags: ['Card Draw'], oracle: 'Whenever an opponent casts a spell, you may draw a card unless that player pays {1}.', colors: ['U'] }),
        card('Lightning Greaves', { type: 'Artifact', roleTags: ['Protection'], oracle: 'Equipped creature has haste and shroud.' }),
        land(7, 'Command Tower', 'Land', []),
        land(6, 'Plains', 'Basic Land — Plains', ['W']),
        land(6, 'Island', 'Basic Land — Island', ['U']),
        land(6, 'Swamp', 'Basic Land — Swamp', ['B']),
        land(6, 'Mountain', 'Basic Land — Mountain', ['R']),
        land(6, 'Forest', 'Basic Land — Forest', ['G']),
      ],
    },
    {
      id: 'yuriko-commander-dependent',
      name: 'Yuriko Commander-Dependent',
      archetype: 'commander-dependent',
      commander: 'Yuriko, the Tiger\'s Shadow',
      colorIdentity: ['U', 'B'],
      plan: {
        winConditionId: 'wincon.combat',
        primaryStrategyId: 'strategy.control',
        competition: 'High',
        playstyleS: 2,
        targetCastTurn: 3,
        castingPattern: 'one_per_turn',
        tutorPreference: 'fine',
        protectionImportance: 'high',
        keyCards: [{ name: 'Yuriko, the Tiger\'s Shadow' }],
      },
      notes: 'Commander-dependent ninjutsu — Keep Going/protection should matter.',
      expected: { closeGameMode: 'combat' },
      cards: [
        cmd('Yuriko, the Tiger\'s Shadow', { cmc: 3, colors: ['U', 'B'] }),
        card('Lightning Greaves', { type: 'Artifact', roleTags: ['Protection'], oracle: 'Equipped creature has haste and shroud.' }),
        card('Counterspell', { roleTags: ['Counterspell'], oracle: 'Counter target spell.', colors: ['U'] }),
        card('Night\'s Whisper', { type: 'Sorcery', roleTags: ['Card Draw'], oracle: 'You draw two cards and you lose 2 life.', colors: ['B'] }),
        land(18, 'Island', 'Basic Land — Island', ['U']),
        land(18, 'Swamp', 'Basic Land — Swamp', ['B']),
      ],
    },
  ];

  return { FOUNDATION_LAB_SUITE_DEFS };
});
